### PR TITLE
Replace next revalidate: 300 with no-store

### PR DESCRIPTION
**Pull request by mxstbr**
This reverts commit 2cba231b696a57522f3463ef70e551571f2b8b88.

### CODE REVIEW

**Comment by mxstbr** [comment]
Why would this change cause this error?! 😵 

CleanShot 2024-08-17 at 14 51 56@2x

```
Error: ENOENT: no such file or directory, scandir '/var/task/app/thoughts'
    at Object.readdirSync (node:fs:1507:26)
    at getMDXFiles (/var/task/.next/server/app/page.js:28:11572)
    at getMDXData (/var/task/.next/server/app/page.js:28:12023)
    at getBlogPosts (/var/task/.next/server/app/page.js:28:12345)
    at o (/var/task/.next/server/app/page.js:28:7310)
    at eh (/var/task/node_modules/.pnpm/next@14.2.3_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134786)
    at e (/var/task/node_modules/.pnpm/next@14.2.3_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:137671)
    at ek (/var/task/node_modules/.pnpm/next@14.2.3_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:138145)
    at Array.toJSON (/var/task/node_modules/.pnpm/next@14.2.3_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135755)
    at stringify (<anonymous>) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/var/task/app/thoughts',
  digest: '2318037785'
}
```

**Comment by leerob** [comment]
I have a feeling it might be related to [this commit](https://github.com/mxstbr/mxstbr.com/commit/c84467868a021d3ae39a9c8033178a7e1fb12556) – I've seen similar errors reported before when using `shiki` because it's trying to use files in `node_modules` that [nft](https://github.com/vercel/nft) isn't aware of when bundling. Could we try ruling that out? Maybe doing a few production builds manually (on the latest `main`) to see if you get the same error here.

**Comment by mxstbr** [comment]
@leerob I can confirm that I don't get this error with any other commit on master. It's just this specific commit that consistently, 100% reproducibly, errors on Vercel. (it also works locally)

**Comment by mxstbr** [comment]
Upgraded to Next, React, & ReactDOM canary; now I get a better error on Vercel!

CleanShot 2024-08-19 at 09 14 50@2x

Again, this commit causes that error, it is not happening on master. I don't know why changing it from revalidate to no-store would cause this error though @leerob 🤔

**Comment by mxstbr** [comment]
Ohh wait. If I don't cache in Vercel's Data Cache, Next.js turns this route into a server-side rendered one? Is that it?

**Comment by leerob** [comment]
Correct. If you don't cache the `fetch`, you are correct that the route becomes dynamically rendered. `no-store` is opting out of caching, so it is using server-side rendering.

**Comment by leerob** [comment]
Maybe it's now trying to read an MDX file on-demand through SSR, which is causing the issue.

**Comment by mxstbr** [comment]
Ahhh, that's it. Thanks for helping me figure it out!

**Pull request closed without merging**
