### PR TITLE
Integrate prettier for mdx

### PR DESCRIPTION
**Pull request by mxstbr**
@johno this fails due to a semicolon that is added by prettier that mdx does not parse correctly:

```
./pages/thoughts/css-in-js.md
SyntaxError: /Users/mxstbr/projects/github/mxstbr/mxstbr.com/pages/thoughts/css-in-js.md: Unexpected token, expected "}" (15:135)

  13 |   image: "/static/images/css-in-js.png"
  14 | };
> 15 | export default ({components, ...props}) => <MDXTag name="wrapper" Layout={({ children }) => <BlogPost meta={meta}>{children}</BlogPost>;} layoutProps={props} components={components}>
     |                                                                                                                                        ^
  16 | 
  17 | 
  18 | <MDXTag name="p" components={components}>{`For three years, I have styled my web apps without any `}<MDXTag name="inlineCode" components={components} parentName="p">{`.css`}</MDXTag>{` files. Instead, I have written all the CSS in JavaScript.`}</MDXTag>

> Build error occurred
Error: > Build failed because of webpack errors
```

Any ideas why that semicolon of the default export is included incorrectly and how to fix this?

### CODE REVIEW

**Comment by johno** [comment]
Oh weird, we _should_ be [handling semicolons](https://github.com/mdx-js/mdx/blob/master/packages/mdx/mdx-hast-to-jsx.js#L46-L48) but it looks like there's been some type of regression. I'll look into it today.

**Comment by johno** [comment]
Looks like it's because `@zeit/next-mdx` v1.2.0 comes along with a very old version of MDX (0.15.0). The canary release correctly doesn't pin an `@mdx-js/loader` version, however it's v1.1.1-canary.4?

Not sure what's going on there.

image

cc/ @timneutkens

**Comment by timneutkens** [comment]
You'll want to use `@next/mdx@canary` for now until the upcoming stable patch release when the plugin will be published as stable. We're moving away from using the `@zeit` namespace for Next.js plugins 👍

**Comment by mxstbr** [comment]
@timneutkens are you going to move Next to `github.com/next/next.js` or something like that?

**Comment by mxstbr** [comment]
Thanks for the quick help here, that seems to have worked! :100:

**Comment by timneutkens** [comment]
@mxstbr nope we're not moving it to another github org, just different npm org as they all fit together with `@next`, previously we didn't have `@next` so we had to publish under `@zeit` as a workaround.

**Pull request merged**
